[package]
name = "fs-id"
version = "0.1.0"
edition = "2021"

[target.'cfg(unix)'.dependencies]
libc = "0.2.152"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["std", "winbase"] }
